package com.bro.steel.entity;

/**
 * @author zhanghonglin
 * @date 2020/12/14 19:11
 * @class TblSupplierInfo
 * @description 描述供应商或客户
 */
public class TblSupplierInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_info.id
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_info.name
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_info.phone
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_info.address
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_supplier_info.type
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_info.id
     *
     * @return the value of tbl_supplier_info.id
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_info.id
     *
     * @param id the value for tbl_supplier_info.id
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_info.name
     *
     * @return the value of tbl_supplier_info.name
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_info.name
     *
     * @param name the value for tbl_supplier_info.name
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_info.phone
     *
     * @return the value of tbl_supplier_info.phone
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_info.phone
     *
     * @param phone the value for tbl_supplier_info.phone
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_info.address
     *
     * @return the value of tbl_supplier_info.address
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_info.address
     *
     * @param address the value for tbl_supplier_info.address
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_supplier_info.type
     *
     * @return the value of tbl_supplier_info.type
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_supplier_info.type
     *
     * @param type the value for tbl_supplier_info.type
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }
}