package com.bro.steel.dao.auto;

import com.bro.steel.entity.TblSupplierInfo;
import com.bro.steel.entity.TblSupplierInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TblSupplierInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_supplier_info
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    int countByExample(TblSupplierInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_supplier_info
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    int deleteByExample(TblSupplierInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_supplier_info
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_supplier_info
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    int insert(TblSupplierInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_supplier_info
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    int insertSelective(TblSupplierInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_supplier_info
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    List<TblSupplierInfo> selectByExample(TblSupplierInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_supplier_info
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    TblSupplierInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_supplier_info
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    int updateByExampleSelective(@Param("record") TblSupplierInfo record, @Param("example") TblSupplierInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_supplier_info
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    int updateByExample(@Param("record") TblSupplierInfo record, @Param("example") TblSupplierInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_supplier_info
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    int updateByPrimaryKeySelective(TblSupplierInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_supplier_info
     *
     * @mbggenerated Mon Dec 14 19:11:30 CST 2020
     */
    int updateByPrimaryKey(TblSupplierInfo record);
}